### ISSUE TITLE
PSR-4 for lib/ClientCredentialsClient.php

### ISSUE THREAD

**Issue by bostin** [criteo/criteo-api-marketingsolutions-php-sdk#5]
According to https://www.php-fig.org/psr/psr-4/:
> The terminating class name corresponds to a file name ending in .php. The file name MUST match the case of the terminating class name.

Can you split ClientCredentialsClient, OAuthClient, Token into different files?

When using this SDK directly, composer will not be able to automatically load `criteo\api\marketingsolutions\v2023_07\OAuthClient`.

Currently I can only manually modify my composer.json file to make the SDK work as expected:
```json
"autoload": {
         "files": [
             "./vendor/criteo/criteo-api-marketingsolutions-sdk/lib/ClientCredentialsClient.php"
         ]
     },
```

**Comment by gturri** [comment]
Thanks for this bug report @bostin . We're on our way to fix it.
We figured out it would not be an issue because we though users would only manipulate directly `ClientCredentialsClient` and not necessarily `OAuthClient` (not directly). So, while we work on a fix, could you give us more clue on how you're using this sdk? (getting a better understanding of how it is used would help us ensure we can keep delivering something useful and efficient in the future).
Thanks!

**Comment by gturri** [comment]
Fixed
